"""Host backend interface (spec §2.1 profiles).

The supervisor drives containment, metering, and effect release through
this boundary.  ``LinuxHost`` performs the real kernel operations;
``SimHost`` is the deterministic mocked reference host used by the
conformance suite (the spec's own testing convention, §7.1/§15.1).
"""

from __future__ import annotations

from typing import Protocol


class HostBackend(Protocol):
    name: str

    def boot_id(self) -> str: ...
    def boottime_us(self) -> int: ...

    # --- capabilities / provisioning ------------------------------------
    def capabilities(self, profile: str) -> dict: ...
    def task_uid_alloc(self, lo: int, hi: int, in_use: set[int]) -> int: ...
    def workspace_lease(self, path: str, run_id: str): ...

    # --- cgroup containment ----------------------------------------------
    def cgroup_create(self, run_id: str, cfg: dict, domain_cpus: str) -> object: ...
    def cgroup_usage_us(self, cg) -> int: ...
    def cgroup_populated(self, cg) -> int: ...
    def cgroup_kill(self, cg) -> bool: ...
    def group_kill(self, cg) -> bool: ...
    def cgroup_teardown(self, cg) -> None: ...

    # --- energy domains ----------------------------------------------------
    def open_domains(self, domain_ids: list[str]) -> list: ...
    def read_domain(self, handle) -> tuple[int, int, int]: ...  # (counter_uj, range_uj, read_t_us)

    # --- workload processes --------------------------------------------------
    def spawn_root(self, run_ctx, execv: dict, channel_sock) -> object: ...
    def spawn_child(self, run_ctx, execv: dict, channel_sock) -> object: ...
    def proc_exited(self, proc) -> dict | None: ...  # Exit or None
    def proc_alive(self, proc) -> bool: ...

    # --- brokered network ------------------------------------------------------
    def http_get(self, dest: dict, action: dict, deadline_us: int) -> dict: ...
